### ISSUE TITLE
Simpler docker usage

### ISSUE THREAD

**Issue by tpluscode** [speced/bikeshed#2089]
I would like to propose much simplified instructions for running from docker locally. Basically all one needs is a docker-compose and a dockerfile to build a local image with an installation of bike shed. No building from sources and manual volume  setup

**.Dockerfile**

```
FROM python:buster

RUN pip install bikeshed
RUN bikeshed update

ENTRYPOINT ["bikeshed"]
CMD ["--help"]
```

**docker-compose.yml**

```
version: "3"
services:
  bikeshed:
    build:
      context: .
      dockerfile: bs.Dockerfile
    volumes:
    - .:/data
```

**Usage**

The usage is as simple as it gets, for example:

```
docker-compose run --rm bikeshed watch /data/spec/index.bs
```
