### ISSUE TITLE
New "style-style-syntax-highlighting" (with two "style-") block inserted

### ISSUE THREAD

**Issue by domenic** [speced/bikeshed#2583]
This seems to have changed recently. It contains only the following:

```css
/* Boilerplate: style-style-syntax-highlighting */

            pre.idl.highlight {
                background: var(--borderedblock-bg, var(--def-bg));
            }
            
```

WHATWG is excluding `style-syntax-highlighting`, but not `style-style-syntax-highlighting`. Presumably the existence of the latter is a bug?
