### ISSUE TITLE
Some inconsistencies in specially recognized paragraphs (notes, examples etc.)

### ISSUE THREAD

**Issue by woutermont** [speced/bikeshed#2626]
When using the short hands provided by bikeshed to create (boxed) asides, I stumble upon some weird behaviour.

The generall rule seems to aim to recognize all keywords, in whatever case, followed by a colon, a comma (notes-only), or a single newline, followed by text.

- Notes seem to follow this, and by default add a numbered label.
- Issues seem to behave similar to notes (excepts the comma syntax does not work).
- Advisements, on the other hand, are merely stylized, without rendering a (counted) label.
- Examples do not seem to be recognized at all in shorthand. Only when explicitly constructing an element with the class `exmple`, does bikeshed provide the expected box with label and counter.
- Assertions, lastly, are impossible to create. neither the shorthand nor adding the expxlicit class makes any change in styling.

Note: I used the plain `bikespec template` of v3.14.3.

I end up writing custon CSS like 

```css
    /* Reset base counters and additional ones */
    body { counter-reset: example note issue assertion advisement figure !important; }

    /* Configure increments for additional counters */
    .note { counter-increment: note; }
    .assertion { counter-increment: assertion; }
    .advisement { counter-increment: advisement; }

    /* Configure display of additional counters */
    .note:not(.no-marker)::before { content: "Note " counter(note); }
    .assertion:not(.no-marker)::before { content: "Assertion" counter(assertion); }
    .advisement:not(.no-marker)::before { content: "Advisement" counter(advisement); }

    /* Reduce font size of and markers */
    .note,
    .issue,
    .example,
    .assertion,
    .advisement { 
      .marker { 
        display: none; 
      }
      font-size: 0.9em; 
    }
    pre { font-size: .8em; }

    /* Style RFC2119 conformance terms */
    em.rfc2119 {
        text-transform: lowercase;
        font-variant: small-caps;
        font-style: normal;
        font-size: 18px;
        color: #900;
    }
```
